[bugfix] Added missing header for cgstokes.
When compiling the pdelab-howto, I got the error:

/home/mblatt/src/dune/current/dune-pdelab-howto/src/navier-stokes/cgstokes.cc: In function ‘void navierstokes(const GV&, std::string, const PRM&, V_FEM&, P_FEM&, IF&)’:
/home/mblatt/src/dune/current/dune-pdelab-howto/src/navier-stokes/cgstokes.cc:149:3: error: ‘Newton’ is not a member of ‘Dune::PDELab’

The header newton.hh was never included which is fixed with this
commit. Seems kind of weired that nobody has noticed this. Must be my
aura ;)